spring.datasource.url=jdbc:postgresql://c4mf833jfd7vec.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d53fo1vu5thi2n


spring.datasource.username=ubgicfnu19i5ue
spring.datasource.password=p17cee7d50bd4543981554e6da2dc76d24cac10e485528894c74844d0ed357a47
spring.jpa.hibernate.ddl-auto=create
