spring.datasource.url=jdbc:postgresql://c4mf833jfd7vec.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d9o086l2jurm9r

spring.datasource.username=u2t4pf86pvnup9
spring.datasource.password=pae60cfc874f8933bbe27b2c06d5fd2e4b3aaac316301798d132eafce569938db

spring.jpa.hibernate.ddl-auto=update

